server.port=8743

# H2 en memoria (no requiere PostgreSQL para Entrega 1)
spring.datasource.url=jdbc:h2:mem:vulncheck
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# ============================================================
# MODO LAB
# ============================================================
wazuh.ssh.enabled=false
wazuh.ssh.host=158.170.12.112
wazuh.ssh.port=22
wazuh.ssh.user=devsecops3
wazuh.ssh.password=usuariocontrase\u00f1a

# Wazuh Indexer (127.0.0.1 = localhost en el servidor via tunel SSH)
wazuh.indexer.remote-host=158.170.12.112
wazuh.indexer.remote-port=9200
wazuh.indexer.local-port=9201
wazuh.indexer.user=usuario1
wazuh.indexer.password=usuariocontrase\u00f1a

# Wazuh Manager API
wazuh.manager.remote-host=127.0.0.1
wazuh.manager.remote-port=55000
wazuh.manager.local-port=55001
wazuh.manager.user=usuario1
wazuh.manager.password=usuariocontrase\u00f1a
